run:
  deadline: 5m

linters:
  disable-all: true
  enable:
    - deadcode
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - structcheck
    - typecheck
    - varcheck
    - goimports
    - gocritic
    - revive

linters-settings:
  revive:
    # see https://github.com/mgechev/revive#available-rules for details.
    rules:
      - name: exported
        arguments : ["disableStutteringCheck"] # to be merged: https://github.com/mgechev/revive/pull/565
