server:
  port: 8091
  maxRollbackRetryTimeout: -1
  maxCommitRetryTimeout: -1
  rollbackRetryTimeoutUnlockEnable: true
  asyncCommittingRetryPeriod: 10s
  committingRetryPeriod: 1s
  rollingBackRetryPeriod: 1s
  timeoutRetryPeriod: 1s
enforcementPolicy:
  minTime: 5s
  permitWithoutStream: true
serverParameters:
  maxConnectionIdle: 15s
  maxConnectionAge: 30s
  maxConnectionAgeGrace: 5s
  time: 5s
  timeout: 1s
clientParameters:
  time: 10s
  timeout: 1s
  permitWithoutStream: true
storage:
  mysql:
    dsn: "root:123456@tcp(127.0.0.1:3306)/seata?timeout=1s&readTimeout=1s&writeTimeout=1s&parseTime=true&loc=Local&charset=utf8mb4,utf8"
    globaltable: global_table2
    branchtable: branch_table2
    locktable: lock_table
    maxopenconnections: 100
    maxidleconnections: 20
    maxlifetime: 4h
log:
  logPath: /Users/scottlewis/dksl/git/1/seata-golang/cmd/profiles/dev/seata.log
  logLevel: info
