# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events for all branches and tags
on:
  push:
    branches: [ '**' ]
  pull_request:
    branches: [ '**' ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "lint"
  lint:
    strategy:
      matrix:
        go-version: [ 1.15.x ]

    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}
      
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Install linters
        run: |
          go get github.com/golangci/golangci-lint/cmd/golangci-lint@v1.39.0
        
      - name: Lint and Vet Go Code
        run: |
          go build ./...
          go vet -v ./...
          golangci-lint run ./...
